### ISSUE TITLE
ValueError: Namespace GExiv2 not available

### ISSUE THREAD

**Issue by ouening** [variety/variety#151]
OS: Linux mint19.1
python3: 3.6.8

Hi, after I installed variety using `sudo python3 setup.py install` and try to run it, i got the errors below:
`
(variety:21303): dbind-WARNING **: 01:36:52.249: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/local/bin/variety", line 38, in <module>
    import variety
  File "/usr/local/lib/python3.6/dist-packages/variety/__init__.py", line 93, in <module>
    from variety import VarietyWindow
  File "/usr/local/lib/python3.6/dist-packages/variety/VarietyWindow.py", line 51, in <module>
    from variety.PreferencesVarietyDialog import PreferencesVarietyDialog
  File "/usr/local/lib/python3.6/dist-packages/variety/PreferencesVarietyDialog.py", line 24, in <module>
    from variety.Util import Util
  File "/usr/local/lib/python3.6/dist-packages/variety/Util.py", line 38, in <module>
    gi.require_version('GExiv2', '0.10')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GExiv2 not available
`
How can I fix it?

**Comment by JamesCropcho** [comment]
Looks like you solved it (?). Let us know if you run into any other issues, and good luck!

**Comment by ouening** [comment]
I installed it using apt install variety, not the latest vetsion, but it works.

**Comment by JamesCropcho** [comment]
Thank you for supplying the useful tip to the community, 周文青.


―James Cropcho
